apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribbonparser
  labels:
    app: ribbonparser
spec:
  selector:
    matchLabels:
      app: ribbonparser
  template:
    metadata:
      labels:
        app: ribbonparser
    spec:
      containers:
      - name: ribbonbe-parse-app
        image: jeremyqzt/ribbonparser
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 200m
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ribbonparser
  labels:
    app: ribbonparser
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8080
    name: 'http-ingress'
  selector:
    app: ribbonparser
