apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribbonparse
  labels:
    app: ribbonparse
spec:
  selector:
    matchLabels:
      app: ribbonparse
  template:
    metadata:
      labels:
        app: ribbonparse
    spec:
      containers:
      - name: ribbonbe-parse-app
        image: jeremyqzt/ribbonparse
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 300m
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ribbonparse
  labels:
    app: ribbonparse
spec:
  type: NodePort
  ports:
  - port: 60000
    targetPort: 8080
    name: 'http-ingress'
  selector:
    app: ribbonparse
