apiVersion: apps/v1
kind: Deployment
metadata:
  name: ribbonparser
  labels:
    app: ribbonparser
spec:
  selector:
    matchLabels:
      app: ribbonparser
  template:
    metadata:
      labels:
        app: ribbonparser
    spec:
      containers:
      - name: ribbonbe-parse-app
        image: $IMAGE
        resources:
          limits:
            cpu: 600m
          requests:
            cpu: 400m
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ribbonparser
  labels:
    app: ribbonparser
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: ribbonparser
