language: eng # As accepted by pytesseract, e.g. "eng+deu"

# Can contain company locations for fuzzy parsing
companys:
  Apple:
    - apple
  Adidas:
    - adidas
  Nike:
    - nike
  Canada Post:
    - canada post
  Canadian Tire:
    - canadian tire
  Walmart:
    - walmart
    - wal-mart
    - wal mart
  Freshco:
    - freshco
  Target:
    - target
  NoFrills:
    - no-frills
    - noFrills
  CVS:
    - cvs
  Amazon:
    - amazon
    - amazom.com
    - amazon.ca
  Costco:
    - costco
    - costco wholesale
  Home Depot:
    - the home depot
    - home depot
  Kroger:
    - the kroger co
    - kroger
  Walgreens:
    - wallgreens boot alliance
    - wallgreen's
    - wallgreen
  Target:
    - target
  Lowes:
    - lowes
    - lowe's
  Albertsons:
    - albertsons
    - albertson's
  Publix:
    - publix's
    - publixs
    - publix super markets
  Best Buy:
    - best buy
  Dollar General:
    - dollar general
  Dollarama:
    - dollarama
  Dollar Tree:
    - dollar tree
  7 Eleven:
    - 7 eleven
    - 7-eleven
  AT&T:
    - at&t
    - at t
  Verizon:
    - verizon
    - verizon wireless
  Kohl:
    - kohl's
    - kohls
    - kohl
  Nordstrom:
    - nordstrom
  Gap:
    - gap
  Macy's:
    - macy
    - macy's
    - macys
  AutoZone:
    - auto zone
    - autozone
  Wayfair:
    - way fair
    - wayfair
  Staples:
    - staples
    - staple
    - staple's
  Foot Locker:
    - foot locker
  Sephora:
    - sephora
  Petco:
    - petco
  Hudson's Bay:
    - the bay
    - hudson bay
    - hudson's bay
    - hudsons bay
  Luluemon:
    - lululemon
  Urban Outfitters:
    - urban outfitters
    - urban outfitter
    - urban outfiters
    - urban outfiter
  Barnes & Noble:
    - barnes noble
    - barn's and noble
    - barnes & noble

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - total
  - grand total
  - grand sum
  - payable
  - sum
  - fee
  - due

subtotal_keys:
  - sub total
  - sum

tax_keys:
  - tax
  - vat
  - hst
  - gst

formats:
  # 
  sum: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'
  #\$?
  # 11.00 # [] is one character # ? 有冇都得 # . 咩都得 # \s 
  # 11,00 
  # 11@01

  # Matches dates like 19.08.15 and 19. 08. 2015  , 19/08/15 and 19/ 08/ 2015  
  # date: '\b([0123]?\d\s?[\.\ /]\s?[01]?\d\s?[\.\ /]\s?(?:20)?\d\d)\b|\b([0123]?\d\s?\/\s?[01]?\d\s?\/\s?(?:20)?\d\d)\b'
  # date: '(0[1-9]|[1-9]|1[0-2])[/.\ ](\d|0\d|1\d|2\d|3[01])[/.\ ](20)?\d{2}|(\d|0\d|1\d|2\d|3[01])[/.\ ](0[1-9]|[1-9]|1[0-2])[/.\ ](20)?\d{2}'
  date: '((0[1-9]|[1-9]|1[0-2])[/.\ \-\,](\d|0\d|1\d|2\d|3[01])[/.\ \-\,](20)?\d{2})|((\d|0\d|1\d|2\d|3[01])[/.\ \-\,](0[1-9]|[1-9]|1[0-2])[/.\ \-\,](20)?\d{2})'
  #(0[1-9]|[1-9]|1[0-2])[/.\ ](\d|0\d|1\d|2\d|3[01])[/.\ ](20)?\d{2}
  #12 20 2095
  #月 日  年

  #
  postal_code: '\b(\d{5})\s+[a-z]'