language: eng # As accepted by pytesseract, e.g. "eng+deu"

# Can contain company locations for fuzzy parsing
companys:
  Apple:
    - apple
    category: 14
  Adidas:
    - adidas
    category: 7
  Nike:
    - nike
    category: 7
  Canada Post:
    - canada post
    category: 11
  Canadian Tire:
    - canadian tire
    category: 12
  Walmart:
    - walmart
    - wal-mart
    - wal mart
    category: 15
  Freshco:
    - freshco
    category: 3
  Target:
    - target
    category: 15
  NoFrills:
    - no-frills
    - noFrills
    category: 3
  CVS:
    - cvs
    category: 10
  Amazon:
    - amazon
    - amazom.com
    - amazon.ca
    category: 16
  Costco:
    - costco
    - costco wholesale
    category: 15
  Home Depot:
    - the home depot
    - home depot
    category: 13
  Kroger:
    - the kroger co
    - kroger
    category: 3
  Walgreens:
    - wallgreens boot alliance
    - wallgreen's
    - wallgreen
    category: 15
  Lowes:
    - lowes
    - lowe's
  Albertsons:
    - albertsons
    - albertson's
    category: 3
  Publix:
    - publix's
    - publixs
    - publix super markets
    category: 3
  Best Buy:
    - best buy
    category: 6
  Dollar General:
    - dollar general
    category: 9
  Dollarama:
    - dollarama
    category: 9
  Dollar Tree:
    - dollar tree
    category: 9
  7 Eleven:
    - 7 eleven
    - 7-eleven
    category: 15
  AT&T:
    - at&t
    - at t
    category: 14
  Verizon:
    - verizon
    - verizon wireless
    category: 14
  Kohl:
    - kohl's
    - kohls
    - kohl
    category: 3
  Nordstrom:
    - nordstrom
    category: 7
  Gap:
    - gap
    category: 7
  Macy's:
    - macy
    - macy's
    - macys
    category: 7
  AutoZone:
    - auto zone
    - autozone
    category: 12
  Wayfair:
    - way fair
    - wayfair
    category: 9
  Staples:
    - staples
    - staple
    - staple's
    category: 9
  Foot Locker:
    - foot locker
    category: 7
  Sephora:
    - sephora
    category: 16
  Petco:
    - petco
    category: 13
  Hudson's Bay:
    - the bay
    - hudson bay
    - hudson's bay
    - hudsons bay
    category: 7
  Luluemon:
    - lululemon
    category: 7
  Urban Outfitters:
    - urban outfitters
    - urban outfitter
    - urban outfiters
    - urban outfiter
    category: 7
  Barnes & Noble:
    - barnes noble
    - barn's and noble
    - barnes & noble
    category: 16

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - total
  - grand total
  - grand sum
  - payable
  - sum
  - fee
  - due

subtotal_keys:
  - sub total
  - sum

tax_keys:
  - tax
  - vat
  - hst
  - gst

formats:
  # 
  sum: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'
  #\$?
  # 11.00 # [] is one character # ? 有冇都得 # . 咩都得 # \s 
  # 11,00 
  # 11@01

  # Matches dates like 19.08.15 and 19. 08. 2015  , 19/08/15 and 19/ 08/ 2015  
  # date: '\b([0123]?\d\s?[\.\ /]\s?[01]?\d\s?[\.\ /]\s?(?:20)?\d\d)\b|\b([0123]?\d\s?\/\s?[01]?\d\s?\/\s?(?:20)?\d\d)\b'
  # date: '(0[1-9]|[1-9]|1[0-2])[/.\ ](\d|0\d|1\d|2\d|3[01])[/.\ ](20)?\d{2}|(\d|0\d|1\d|2\d|3[01])[/.\ ](0[1-9]|[1-9]|1[0-2])[/.\ ](20)?\d{2}'
  date: '((0[1-9]|[1-9]|1[0-2])[/.\ \-\,](\d|0\d|1\d|2\d|3[01])[/.\ \-\,](20)?\d{2})|((\d|0\d|1\d|2\d|3[01])[/.\ \-\,](0[1-9]|[1-9]|1[0-2])[/.\ \-\,](20)?\d{2})'
  #(0[1-9]|[1-9]|1[0-2])[/.\ ](\d|0\d|1\d|2\d|3[01])[/.\ ](20)?\d{2}
  #12 20 2095
  #月 日  年

  #
  postal_code: '\b(\d{5})\s+[a-z]'