language: eng # As accepted by pytesseract, e.g. "eng+deu"

# Can contain company locations for fuzzy parsing
companys:
  Apple:
    keywords:
      - apple
    category: 14
  Adidas:
    keywords:
      - adidas
    category: 7
  Nike:
    keywords:
      - nike
    category: 7
  Canada Post:
    keywords:
      - canada post
    category: 11
  Canadian Tire:
    keywords:
      - canadian tire
    category: 12
  Walmart:
    keywords:
      - walmart
      - wal-mart
      - wal mart
    category: 15
  Freshco:
    keywords:
      - freshco
    category: 3
  Target:
    keywords:
      - target
    category: 15
  NoFrills:
    keywords:
      - no-frills
      - noFrills
    category: 3
  CVS:
    keywords:
      - cvs
    category: 10
  Amazon:
    keywords:
      - amazon
      - amazom.com
      - amazon.ca
    category: 16
  Costco:
    keywords:
      - costco
      - costco wholesale
    category: 15
  Home Depot:
    keywords:
      - the home depot
      - home depot
    category: 13
  Kroger:
    keywords:
      - the kroger co
      - kroger
    category: 3
  Walgreens:
    keywords:
      - wallgreens boot alliance
      - wallgreen's
      - wallgreen
    category: 15
  Lowes:
    keywords:
      - lowes
      - lowe's
  Albertsons:
    keywords:
      - albertsons
      - albertson's
    category: 3
  Publix:
    keywords:
      - publix's
      - publixs
      - publix super markets
    category: 3
  Best Buy:
    keywords:
      - best buy
    category: 6
  Dollar General:
    keywords:
      - dollar general
    category: 9
  Dollarama:
    keywords:
      - dollarama
    category: 9
  Dollar Tree:
    keywords:
      - dollar tree
    category: 9
  7 Eleven:
    keywords:
      - 7 eleven
      - 7-eleven
    category: 15
  AT&T:
    keywords:
      - at&t
      - at t
    category: 14
  Verizon:
    keywords:
      - verizon
      - verizon wireless
    category: 14
  Kohl:
    keywords:
      - kohl's
      - kohls
      - kohl
    category: 3
  Nordstrom:
    keywords:
      - nordstrom
    category: 7
  Gap:
    keywords:
      - gap
    category: 7
  Macy's:
    keywords:
      - macy
      - macy's
      - macys
    category: 7
  AutoZone:
    keywords:
      - auto zone
      - autozone
    category: 12
  Wayfair:
    keywords:
      - way fair
      - wayfair
    category: 9
  Staples:
    keywords:
      - staples
      - staple
      - staple's
    category: 9
  Foot Locker:
    keywords:
      - foot locker
    category: 7
  Sephora:
    keywords:
      - sephora
    category: 16
  Petco:
    keywords:
      - petco
    category: 13
  Hudson's Bay:
    keywords:
      - the bay
      - hudson bay
      - hudson's bay
      - hudsons bay
    category: 7
  Luluemon:
    keywords:
      - lululemon
    category: 7
  Urban Outfitters:
    keywords:
      - urban outfitters
      - urban outfitter
      - urban outfiters
      - urban outfiter
    category: 7
  Barnes & Noble:
    keywords:
      - barnes noble
      - barn's and noble
      - barnes & noble
    category: 16

# Sum keys roughly ordered by likelyhood.
sum_keys:
  - total
  - grand total
  - grand sum
  - payable
  - sum
  - fee
  - due

subtotal_keys:
  - sub total
  - sum

tax_keys:
  - tax
  - vat
  - hst
  - gst

formats:
  #
  sum: '\d+(\.\s?|,\s?|[^a-zA-Z\d])\d{2}'
  #\$?
  # 11.00 # [] is one character # ? 有冇都得 # . 咩都得 # \s
  # 11,00
  # 11@01

  # Matches dates like 19.08.15 and 19. 08. 2015  , 19/08/15 and 19/ 08/ 2015
  # date: '\b([0123]?\d\s?[\.\ /]\s?[01]?\d\s?[\.\ /]\s?(?:20)?\d\d)\b|\b([0123]?\d\s?\/\s?[01]?\d\s?\/\s?(?:20)?\d\d)\b'
  # date: '(0[1-9]|[1-9]|1[0-2])[/.\ ](\d|0\d|1\d|2\d|3[01])[/.\ ](20)?\d{2}|(\d|0\d|1\d|2\d|3[01])[/.\ ](0[1-9]|[1-9]|1[0-2])[/.\ ](20)?\d{2}'
  date: '((0[1-9]|[1-9]|1[0-2])[/.\ \-\,](\d|0\d|1\d|2\d|3[01])[/.\ \-\,](20)?\d{2})|((\d|0\d|1\d|2\d|3[01])[/.\ \-\,](0[1-9]|[1-9]|1[0-2])[/.\ \-\,](20)?\d{2})'
  #(0[1-9]|[1-9]|1[0-2])[/.\ ](\d|0\d|1\d|2\d|3[01])[/.\ ](20)?\d{2}
  #12 20 2095
  #月 日  年

  #
  postal_code: '\b(\d{5})\s+[a-z]'
